# Change these first
owner: live-codes # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: LiveCodes
    url: https://livecodes.io
  - name: LiveCodes Sandbox
    url: https://livecodes-sandbox.pages.dev/v6/result

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.livecodes.io
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/live-codes/livecodes/develop/images/logo/livecodes-logo.svg
  name: Upptime
  introTitle: "**LiveCodes** - Code Playground That Just Works!"
  introMessage: This is the uptime status page for the LiveCodes app.
  navbar:
    - title: App
      href: https://livecodes.io/
    - title: Docs
      href: https://livecodes.io/docs/
    - title: GitHub
      href: https://github.com/live-codes/livecodes/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
